site_name: Triple-N Dataset Documentation

theme:
  name: material

nav:
  - General: index.md
  - How to get data: howtogetdata.md
  - Processed Files: ProccessedFiles.md
  - MetaData: MetaData.md
  - Code: Code.md
  - Behavioral Software: MonkeyLogic.md